name: ansible-sign-spiffe
on:
  workflow_dispatch:
  push:
    branches:
      - gh-action
jobs:
  ansible-sign-spiffe:
    name: ansible-sign-spiffe
    runs-on: [self-hosted, linux]
    env:
      SPIRE_VERSION: 1.8.2
    steps:
      - name: Checkout Wildfly Project to Sign
        uses: actions/checkout@v4
        with:
          repository: ansible-middleware/wildfly
          path: wildfly
      - name: Checkout ansible-sign Project
        uses: actions/checkout@v4
        with:
          repository: mayaCostantini/ansible-sign
          path: ansible-sign
          ref: sigstorev2-support
      - name: Configure Python Dependencies
        run: |
          set -e
          python -m pip install -U --user pip setuptools setuptools_scm wheel
          cd ansible-sign
          python setup.py bdist_wheel
          python -m pip install --user dist/*
          cd ..
          echo /home/github/.local/bin >> $GITHUB_PATH
      - name: Download spire-agent and obtain JWT
        id: spire-agent
        run: |
          set -e
          curl -LO https://github.com/spiffe/spire/releases/download/v${{ env.SPIRE_VERSION }}/spire-${{ env.SPIRE_VERSION }}-linux-amd64-musl.tar.gz
          tar -xzvf spire-${{ env.SPIRE_VERSION }}-linux-amd64-musl.tar.gz
          JWT=$(spire-${{ env.SPIRE_VERSION }}/bin/spire-agent api fetch jwt -audience=sigstore -socketPath=${SPIFFE_ENDPOINT_SOCKET} | head -2 | sed -n '2 p' | xargs)
          echo spire_jwt=$JWT >> $GITHUB_OUTPUT
      - name: Configure Project Signing
        run: |
          set -e
          cat << EOF > wildfly/MANIFEST.in
          recursive-include playbooks *.yml
          recursive-include roles *.yml
          EOF

      - name: Download Rekor and CT log
        run: |
          set -e

          # Download Rekor Certificate
          curl -L -o rekor.pub ${{ vars.TUF_URL }}/targets/rekor-pubkey

          # Download CT log Certificate
          curl -L -o ctfe.pub ${{ vars.TUF_URL }}/targets/ctfe.pub

          # Download Fulcio Certificate
          curl -L -o fulcio.crt ${{ vars.TUF_URL }}/targets/fulcio-cert

      - name: Sign Project
        uses: sabre1041/sigstore-ansible-github-action@enhancements
        with:
          project_path: "./wildfly"
          identity-token: ${{ steps.spire-agent.outputs.spire_jwt }}
          fulcio-url: "${{ vars.FULCIO_URL }}"
          rekor-url: "${{ vars.REKOR_URL }}"
          install-ansible-sign: 'false'
          ctfe: ctfe.pub
          rekor-root-pubkey: rekor.pub
          push-artifacts: 'false'
          verify: true
          verify-cert-identity: "${{ vars.CERT_IDENTITY }}"
          verify-oidc-issuer: "${{ vars.OIDC_URL }}"
          verify-certificate-chain: fulcio.crt
          internal-be-careful-debug: true

